public class abc3 {
    public decimal a{get;set;}
    public decimal b{get;set;}
    public decimal total{get;set;}
    public void add()
    {
        total=a+b;
    }
    public void mul()
    {
        total=a*b;
        //this is a change created in intelliJ
    }
    public void sub(){
        total=a-b;
    }
    public void dummy(){
        //this is  a dummy message to check the update at 3:33pm
    }
}