public class apexList_example2 {
  //public rapperList_example2 r;
    public string name{get;set;}
    public string industry {get;set;}
    public string rating{get;set;}
    void apexList_example2()
    {
    
      
       // r=new rapperList_example2();
        //List<account> a=new List<account>();
        
    }
    public void create()
    {
        
           account acc=new account();
            //r=new rapperList_example2();
            
         
       
    }

}