public class DisplayingChildFromParent {
/*<apex:page standardController="Customer_BANK__c" recordSetVar="list">
    <apex:pageblock >
    <apex:pageblocktable value="{!list}" var="a" border="5" rules="cols" >
        <apex:column >
         <apex:dataTable value="{!a.loan_bank__r}" var="c">
        <apex:column headerValue="name" value="{!c.Security__c}"/>
            <apex:column headerValue="type" value="{!c.Loan_Type__c}"/>
       </apex:dataTable>
        </apex:column>
        </apex:pageblocktable>
    </apex:pageblock>
</apex:page>

<!--
<apex:page standardController="Opportunity" recordSetVar="items">
    <apex:form >
        <style>
           .one{
        	background:grey;
           }
        </style>
        <apex:dataTable value="{!items}" var="a" width="1000" cellpadding="10" rules="rows" frame="border" headerClass="one" >
            <apex:column >
                <apex:facet name="header"><apex:inputCheckbox /></apex:facet>
                <apex:inputCheckbox />
            </apex:column>
        	<apex:column headerValue="Action">
                <apex:commandLink value="Edit" action="{!URLFOR($Action.Opportunity.Edit,a.id)}" />
               &nbsp; | &nbsp;
                <apex:commandLink value="Del" action="{!URLFOR($Action.Opportunity.Delete,a.id)}" />
            </apex:column>
            <apex:column value="{!a.name}" headerValue="OpportunityName" />
            <apex:column value="{!a.stageName}" headerValue="StageName" />
            <apex:column value="{!a.amount}" headerValue="Amount" />
            <apex:column value="{!a.closeDate}" headerValue="CloseDate" />
            <apex:column value="{!a.Account.Name}" headerValue="Account Name" />
            <apex:column value="{!a.Account.Phone}" headerValue="Phone" />
        </apex:dataTable>
   </apex:form>
</apex:page>-->
*/
}